### ISSUE TITLE
20211113練習問題

### ISSUE THREAD

**Issue by yokikoshimizu** [yokikoshimizu/yokikoshimizu_repository#2]
@SatakeYusuke19920527 
練習問題1つ目、プッシュしておいたのでご確認ください！

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
2つ目もプッシュしました！ご確認ください！

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
3つ目もプッシュしました！ご確認ください！

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
4問全てプッシュしました！ご確認よろしくお願い致します！

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
おはようございます！

4問目のCSSを修正してみました。

■background-colorの重複を消しました
（※topもまとめようかと思いましたが逆に分かりにくくなるかと思ってそのままにしています）
■relativeで位置設定していたhtmlの親BOX（.wrap）に縦横の大きさを設定して、
子になるabsoluteのBOXにtopとleftではなく、bottomとrightを使って位置設定をしてみました。
距離が近い位置からpxを書く方がより分かりやすいのかな…？

以上プッシュしておきましたので、ご確認お願いいたします！

**Comment by SatakeYusuke19920527** [comment]
いい感じですね。
以下、コメントです。

■background-colorの重複を消しました
（※topもまとめようかと思いましたが逆に分かりにくくなるかと思ってそのままにしています）
→これは最高です。これからコード量が膨大になっていくので、どんどんまとめてもらうとコードの見通しがよくなり、開発スピードがどんどん上がってきます。コンポーネント志向というので、是非調べてみてください。
> https://qiita.com/teradonburi/items/6828635d2e70dba6637d 

■relativeで位置設定していたhtmlの親BOX（.wrap）に縦横の大きさを設定して、
子になるabsoluteのBOXにtopとleftではなく、bottomとrightを使って位置設定をしてみました。
距離が近い位置からpxを書く方がより分かりやすいのかな…？
→これもいい修正ですね。位置指定の方法は講義で教えたposition: relativeの他にdisplay: flexという方法もあります。
これも是非調べてみてください！
> https://www.webcreatorbox.com/tech/css-flexbox-cheat-sheet

**Comment by yokikoshimizu** [comment]
こちら閉じておきます！
